//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMisMobilePortal.UserAuthentication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResult", Namespace="http://auth.app.com.cn/")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SucceedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succeed {
            get {
                return this.SucceedField;
            }
            set {
                if ((this.SucceedField.Equals(value) != true)) {
                    this.SucceedField = value;
                    this.RaisePropertyChanged("Succeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://auth.app.com.cn/", ConfigurationName="UserAuthentication.UserAuthenticationSoap")]
    public interface UserAuthenticationSoap {
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 GetCompanyAuthUrlListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/GetCompanyAuthUrlList", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse GetCompanyAuthUrlList(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/GetCompanyAuthUrlList", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse> GetCompanyAuthUrlListAsync(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/SAPUserAuthentication", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse SAPUserAuthentication(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/SAPUserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse> SAPUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/SAPUserAuthenticationJson", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse SAPUserAuthenticationJson(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/SAPUserAuthenticationJson", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse> SAPUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/OAUserAuthentication", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse OAUserAuthentication(iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/OAUserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse> OAUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/OAUserAuthenticationJson", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse OAUserAuthenticationJson(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/OAUserAuthenticationJson", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse> OAUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/ADUserAuthentication", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse ADUserAuthentication(iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/ADUserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse> ADUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest request);
        
        // CODEGEN: 命名空间 http://auth.app.com.cn/ 的元素名称 accessToken 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/ADUserAuthenticationJson", ReplyAction="*")]
        iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse ADUserAuthenticationJson(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://auth.app.com.cn/ADUserAuthenticationJson", ReplyAction="*")]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse> ADUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyAuthUrlListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyAuthUrlList", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequestBody Body;
        
        public GetCompanyAuthUrlListRequest() {
        }
        
        public GetCompanyAuthUrlListRequest(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCompanyAuthUrlListRequestBody {
        
        public GetCompanyAuthUrlListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyAuthUrlListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyAuthUrlListResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponseBody Body;
        
        public GetCompanyAuthUrlListResponse() {
        }
        
        public GetCompanyAuthUrlListResponse(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class GetCompanyAuthUrlListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCompanyAuthUrlListResult;
        
        public GetCompanyAuthUrlListResponseBody() {
        }
        
        public GetCompanyAuthUrlListResponseBody(string GetCompanyAuthUrlListResult) {
            this.GetCompanyAuthUrlListResult = GetCompanyAuthUrlListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SAPUserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SAPUserAuthentication", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequestBody Body;
        
        public SAPUserAuthenticationRequest() {
        }
        
        public SAPUserAuthenticationRequest(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class SAPUserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public SAPUserAuthenticationRequestBody() {
        }
        
        public SAPUserAuthenticationRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SAPUserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SAPUserAuthenticationResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponseBody Body;
        
        public SAPUserAuthenticationResponse() {
        }
        
        public SAPUserAuthenticationResponse(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class SAPUserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMisMobilePortal.UserAuthentication.AuthenticationResult SAPUserAuthenticationResult;
        
        public SAPUserAuthenticationResponseBody() {
        }
        
        public SAPUserAuthenticationResponseBody(iMisMobilePortal.UserAuthentication.AuthenticationResult SAPUserAuthenticationResult) {
            this.SAPUserAuthenticationResult = SAPUserAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SAPUserAuthenticationJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SAPUserAuthenticationJson", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequestBody Body;
        
        public SAPUserAuthenticationJsonRequest() {
        }
        
        public SAPUserAuthenticationJsonRequest(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class SAPUserAuthenticationJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public SAPUserAuthenticationJsonRequestBody() {
        }
        
        public SAPUserAuthenticationJsonRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SAPUserAuthenticationJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SAPUserAuthenticationJsonResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponseBody Body;
        
        public SAPUserAuthenticationJsonResponse() {
        }
        
        public SAPUserAuthenticationJsonResponse(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class SAPUserAuthenticationJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SAPUserAuthenticationJsonResult;
        
        public SAPUserAuthenticationJsonResponseBody() {
        }
        
        public SAPUserAuthenticationJsonResponseBody(string SAPUserAuthenticationJsonResult) {
            this.SAPUserAuthenticationJsonResult = SAPUserAuthenticationJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAUserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAUserAuthentication", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequestBody Body;
        
        public OAUserAuthenticationRequest() {
        }
        
        public OAUserAuthenticationRequest(iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class OAUserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public OAUserAuthenticationRequestBody() {
        }
        
        public OAUserAuthenticationRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAUserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAUserAuthenticationResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponseBody Body;
        
        public OAUserAuthenticationResponse() {
        }
        
        public OAUserAuthenticationResponse(iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class OAUserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMisMobilePortal.UserAuthentication.AuthenticationResult OAUserAuthenticationResult;
        
        public OAUserAuthenticationResponseBody() {
        }
        
        public OAUserAuthenticationResponseBody(iMisMobilePortal.UserAuthentication.AuthenticationResult OAUserAuthenticationResult) {
            this.OAUserAuthenticationResult = OAUserAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAUserAuthenticationJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAUserAuthenticationJson", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequestBody Body;
        
        public OAUserAuthenticationJsonRequest() {
        }
        
        public OAUserAuthenticationJsonRequest(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class OAUserAuthenticationJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public OAUserAuthenticationJsonRequestBody() {
        }
        
        public OAUserAuthenticationJsonRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAUserAuthenticationJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAUserAuthenticationJsonResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponseBody Body;
        
        public OAUserAuthenticationJsonResponse() {
        }
        
        public OAUserAuthenticationJsonResponse(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class OAUserAuthenticationJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OAUserAuthenticationJsonResult;
        
        public OAUserAuthenticationJsonResponseBody() {
        }
        
        public OAUserAuthenticationJsonResponseBody(string OAUserAuthenticationJsonResult) {
            this.OAUserAuthenticationJsonResult = OAUserAuthenticationJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADUserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADUserAuthentication", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequestBody Body;
        
        public ADUserAuthenticationRequest() {
        }
        
        public ADUserAuthenticationRequest(iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class ADUserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public ADUserAuthenticationRequestBody() {
        }
        
        public ADUserAuthenticationRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADUserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADUserAuthenticationResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponseBody Body;
        
        public ADUserAuthenticationResponse() {
        }
        
        public ADUserAuthenticationResponse(iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class ADUserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public iMisMobilePortal.UserAuthentication.AuthenticationResult ADUserAuthenticationResult;
        
        public ADUserAuthenticationResponseBody() {
        }
        
        public ADUserAuthenticationResponseBody(iMisMobilePortal.UserAuthentication.AuthenticationResult ADUserAuthenticationResult) {
            this.ADUserAuthenticationResult = ADUserAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADUserAuthenticationJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADUserAuthenticationJson", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequestBody Body;
        
        public ADUserAuthenticationJsonRequest() {
        }
        
        public ADUserAuthenticationJsonRequest(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class ADUserAuthenticationJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accessToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public ADUserAuthenticationJsonRequestBody() {
        }
        
        public ADUserAuthenticationJsonRequestBody(string accessToken, string userName, string password) {
            this.accessToken = accessToken;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADUserAuthenticationJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADUserAuthenticationJsonResponse", Namespace="http://auth.app.com.cn/", Order=0)]
        public iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponseBody Body;
        
        public ADUserAuthenticationJsonResponse() {
        }
        
        public ADUserAuthenticationJsonResponse(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://auth.app.com.cn/")]
    public partial class ADUserAuthenticationJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ADUserAuthenticationJsonResult;
        
        public ADUserAuthenticationJsonResponseBody() {
        }
        
        public ADUserAuthenticationJsonResponseBody(string ADUserAuthenticationJsonResult) {
            this.ADUserAuthenticationJsonResult = ADUserAuthenticationJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserAuthenticationSoapChannel : iMisMobilePortal.UserAuthentication.UserAuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAuthenticationSoapClient : System.ServiceModel.ClientBase<iMisMobilePortal.UserAuthentication.UserAuthenticationSoap>, iMisMobilePortal.UserAuthentication.UserAuthenticationSoap {
        
        public UserAuthenticationSoapClient() {
        }
        
        public UserAuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.GetCompanyAuthUrlList(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest request) {
            return base.Channel.GetCompanyAuthUrlList(request);
        }
        
        public string GetCompanyAuthUrlList() {
            iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest inValue = new iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequestBody();
            iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).GetCompanyAuthUrlList(inValue);
            return retVal.Body.GetCompanyAuthUrlListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.GetCompanyAuthUrlListAsync(iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest request) {
            return base.Channel.GetCompanyAuthUrlListAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListResponse> GetCompanyAuthUrlListAsync() {
            iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest inValue = new iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.GetCompanyAuthUrlListRequestBody();
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).GetCompanyAuthUrlListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.SAPUserAuthentication(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest request) {
            return base.Channel.SAPUserAuthentication(request);
        }
        
        public iMisMobilePortal.UserAuthentication.AuthenticationResult SAPUserAuthentication(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).SAPUserAuthentication(inValue);
            return retVal.Body.SAPUserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.SAPUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest request) {
            return base.Channel.SAPUserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationResponse> SAPUserAuthenticationAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).SAPUserAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.SAPUserAuthenticationJson(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest request) {
            return base.Channel.SAPUserAuthenticationJson(request);
        }
        
        public string SAPUserAuthenticationJson(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).SAPUserAuthenticationJson(inValue);
            return retVal.Body.SAPUserAuthenticationJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.SAPUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest request) {
            return base.Channel.SAPUserAuthenticationJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonResponse> SAPUserAuthenticationJsonAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.SAPUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).SAPUserAuthenticationJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.OAUserAuthentication(iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest request) {
            return base.Channel.OAUserAuthentication(request);
        }
        
        public iMisMobilePortal.UserAuthentication.AuthenticationResult OAUserAuthentication(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).OAUserAuthentication(inValue);
            return retVal.Body.OAUserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.OAUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest request) {
            return base.Channel.OAUserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationResponse> OAUserAuthenticationAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).OAUserAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.OAUserAuthenticationJson(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest request) {
            return base.Channel.OAUserAuthenticationJson(request);
        }
        
        public string OAUserAuthenticationJson(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).OAUserAuthenticationJson(inValue);
            return retVal.Body.OAUserAuthenticationJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.OAUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest request) {
            return base.Channel.OAUserAuthenticationJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonResponse> OAUserAuthenticationJsonAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.OAUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).OAUserAuthenticationJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.ADUserAuthentication(iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest request) {
            return base.Channel.ADUserAuthentication(request);
        }
        
        public iMisMobilePortal.UserAuthentication.AuthenticationResult ADUserAuthentication(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).ADUserAuthentication(inValue);
            return retVal.Body.ADUserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.ADUserAuthenticationAsync(iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest request) {
            return base.Channel.ADUserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationResponse> ADUserAuthenticationAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest inValue = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).ADUserAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.ADUserAuthenticationJson(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest request) {
            return base.Channel.ADUserAuthenticationJson(request);
        }
        
        public string ADUserAuthenticationJson(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse retVal = ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).ADUserAuthenticationJson(inValue);
            return retVal.Body.ADUserAuthenticationJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse> iMisMobilePortal.UserAuthentication.UserAuthenticationSoap.ADUserAuthenticationJsonAsync(iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest request) {
            return base.Channel.ADUserAuthenticationJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonResponse> ADUserAuthenticationJsonAsync(string accessToken, string userName, string password) {
            iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest inValue = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequest();
            inValue.Body = new iMisMobilePortal.UserAuthentication.ADUserAuthenticationJsonRequestBody();
            inValue.Body.accessToken = accessToken;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((iMisMobilePortal.UserAuthentication.UserAuthenticationSoap)(this)).ADUserAuthenticationJsonAsync(inValue);
        }
    }
}
